WIDTH = 40
HEIGHT = 25
SCALE = 30
RADIUS = 5
ELEMENT_SIZE = 28
FPS = 60
INITIAL_SPEED_DELAY = FPS // 6
SNAKE_COLOR = "yellow"
APPLE_COLOR = "red"
SCORE_COLOR = "white"
SCREEN_COLOR = "black"
GAME_OVER_COLOR = "red"
# Цвета еды
NORMAL_FOOD_COLOR = "red"
SPEED_FOOD_COLOR = "cyan"
SHRINK_FOOD_COLOR = "white"