WIDTH = 25
HEIGHT = 20
SCALE = 40
RADIUS = 5
ELEMENT_SIZE = 38
FPS = 60
INITIAL_SPEED_DELAY = FPS // 6
SNAKE_COLOR = "yellow"
APPLE_COLOR = "red"
SCORE_COLOR = "white"
SCREEN_COLOR = "black"
GAME_OVER_COLOR = "red"
# Цвета еды
NORMAL_FOOD_COLOR = "red"
SPEED_FOOD_COLOR = "blue"
SHRINK_FOOD_COLOR = "white"